### PR TITLE
added french translation

### PR DESCRIPTION
**Pull request by lucasgehin**
added french translation

### CODE REVIEW

**Comment by dmolineus** [comment]
Thanks for the translation. I merged your pull request. However, as the translations are managed by transifex, It would be great if you use it to translate the project.

https://www.transifex.com/contao-bootstrap/contao-bootstrap

**Comment by dmolineus** [comment]
I manually imported your translations to transifex now.

**Comment by lucasgehin** [comment]
Yeah i requested acces for transifex few months ago (at the same time as my
pull request) but got no answer ..
Le lun. 1 août 2016 à 12:23, David Molineus <notifications@github.com> a
écrit :

**Comment by dmolineus** [comment]
Sorry, I was really busy and didn't get any notifications from transifex. I just added you to the transifex project.

**Pull request merged**
